### ISSUE TITLE
About the overall training time.

### ISSUE THREAD

**Issue by Liu-zhi-chao** [georgeliu233/DP3#3]
Hello, thank you very much for your excellent work!

Could you please tell me the approximate time required to train each module with 4 A100 GPUs?
For example, how long does it take to train each module in nuScenes, WOMD and CARLA benchmark? This will be very helpful to me.

Looking forward to your reply!

**Comment by georgeliu233** [comment]
Hi, thanks for your interest in our project!

For end-to-end training in NuScenes, it requires 3-4 days for stage2 training leveraging pretrained perception weights.
For training in WOMD and CARLA, it requires <2 days without the perception bottleneck.
